console.log("Hola hola")
console.log("Adios Adios")
console.log("Que me vez")
console.log("Que me vez")
console.log("Que me vez")
console.log("Que me vez")
console.log("Que me vez")
console.log("Que me vez")
console.log("Que me vez")
console.log("Que me vez")
console.log("Que me vez")
console.log("Que me vez")
console.log("Que me vez")
console.log("Que me vez")
console.log("Que me vez")
console.log("Que me vez")
console.log("Que me vez")
console.log("Que me vez")
console.log("Que me vez")
console.log("Que me vez")
console.log("Que me vez")
console.log("Que me vez")
console.log("Que me vez")
console.log("Que me vez")